version: '3'

services:

  frontend:
    image: frontend
    ports:
      - "8080:8080"
    volumes:
      - frontend-data:/data
    build: ./frontend

  backend:
    image: backend
    ports:
      - "8000:8000"
    volumes:
      - backend-data:/data
    build: ./backend
    depends_on:
      - database

  database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=12345
volumes:
  frontend-data:
  backend-data:

